services:
  - type: web
    name: sarkaari-yojana-backend
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: HUGGINGFACE_API_KEY
        sync: false